OfficeDev/ews-java-api

.idea/libraries/Maven__joda_time_joda_time_2_7.xml
ews-java-api.iml
pom.xml
src/main/java/microsoft/exchange/webservices/data/util/DateTimeParser.java
src/test/java/microsoft/exchange/webservices/data/util/DateTimeParserTest.java

I have included joda-time as a dependency. It may seem overkill for fixing this issue, but if we do include it now we're able to use it on other places in the future.
Fixes #181.

Fix timezone parsing in DateTimeParser with Java 6

---

src/main/java/microsoft/exchange/webservices/data/AttachmentCollection.java

In ```AttachmentCollection.validate()```, type checking added to casting of ```Attachment``` to ```FileAttachment``` as fix for #18.

Fix for AttachmentCollection validate

---

src/main/java/microsoft/exchange/webservices/data/PropertySet.java

When it throws ServiceValidationException, '%s' is output to the log.
```
Caused by: microsoft.exchange.webservices.data.ServiceValidationException: ServiceValidationException :The property %s can't be used in %s requests.,null,FindItem
at microsoft.exchange.webservices.data.PropertySet.validateForRequest(PropertySet.java:481)
at microsoft.exchange.webservices.data.ViewBase.internalValidate(ViewBase.java:43)
at microsoft.exchange.webservices.data.PagedView.internalValidate(PagedView.java:104)
at microsoft.exchange.webservices.data.ItemView.internalValidate(ItemView.java:60)
at microsoft.exchange.webservices.data.FindRequest.validate(FindRequest.java:64)
at microsoft.exchange.webservices.data.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:621)
at …
```

Bad error message of ServiceValidationException

---

pom.xml
readme.md

This PR is about Issue: #1. But also adds inprovements for building a local Jar-File.
We are able to create Jars easily now `mvn clean install` provides 3 jars now (`PROJECT_ROOT\target`):
* ews-java-api-1.3-SNAPSHOT.jar
* ews-java-api-1.3-SNAPSHOT-javadoc.jar
* ews-java-api-1.3-SNAPSHOT-sources.jar
I also added the ability for deploying to sonatype by integrating `nexus-staging-maven-plugin`.
`mvn clean deploy` will now publish jars to sonatype if valid credentials are stored in settings.xml (just tested until the upload cause I dont have the credentials). If the release-name end with snapshot it will automaticly been stored to snapshot repo.
settings.xml (`~/.m2/settings.xml`) should look like this:
```xml
<settings>
...
<servers>
...
<server>
<id>ossrh</id>  
<username>Jira …
```

Deploy artifacts to maven central

---

.travis.yml
pom.xml

As mentioned in #181 we ran into issues because there where differences in the used jdk. This PR tries to prevent this in the future by adding maven profiles for travis-ci which will now build the api against all available jdk's. This also prevents the build from failing while compiling with jdk1.8 with enabled doclint function.

Building against multiple jdk

---

src/main/java/microsoft/exchange/webservices/data/ServiceRequestBase.java

The request isn't returned and can't be closed by the caller in case of an `HttpErrorException`.

Properly close request when HttpErrorException is encountered

---

src/main/java/microsoft/exchange/webservices/data/util/DateTimeParser.java
src/test/java/microsoft/exchange/webservices/data/util/DateTimeParserTest.java

Even though the example in #206 is a bit special (max-date?) the pattern can be supported. Added datePattern and a test.

Added more date-patterns and a test to resolve the milliseconds issue

---

src/main/java/microsoft/exchange/webservices/data/CookieProcessingTargetAuthenticationStrategy.java
src/main/java/microsoft/exchange/webservices/data/ExchangeServiceBase.java

Fixes OfficeDev/ews-java-api#188
It's a bit of a hack, see the discussion in https://issues.apache.org/jira/browse/HTTPCLIENT-1451
The `getChallenges()` method of the `AuthenticationStrategy` seems to be the only place where we have the actual response available - in other places we would need to use the `HttpContext`, but the response has not been saved in the context yet.

Add CookieProcessingTargetAuthenticationStrategy.java

---

src/main/java/microsoft/exchange/webservices/data/HangingServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/HttpClientWebRequest.java
src/main/java/microsoft/exchange/webservices/data/HttpWebRequest.java

We now try to keep the connection alive by simply consuming the full response. If that does not work, we revert to the old behaviour (to make sure we always close the underlying resources).
This is a bit of a hack, but the whole library is still build around the HttpClient 3 behaviour (where you had to close the request), whereas in HttpClient you have to consume the response (or close the request if there is no response, imho this is a flaw in the API of HttpClient 4).

Fix keep-alive handling.

---

src/main/java/microsoft/exchange/webservices/data/EwsXmlReader.java

I faced with a performance problem. To investigate this issue, I run `ExchangeService.findAppointments` many times and got the following summary statistic:
* ExchangeService.findAppointments - 102 sec.
* EwsXmlReader.readValue - 21 sec.
* String.format - 14 sec.
EwsXmlReader.readValue uses String.format always (even when it is completely unnecessary). This PR improves this situation and prevents all unnecessary calls of String.format in this method.
It is only the one place where we can improve `ExchangeService.findAppointments`. I decided to not send all improvements to simplify code review.

Optimize EwsXmlReader.readValue

---

src/main/java/microsoft/exchange/webservices/data/DelegateManagementRequestBase.java
src/main/java/microsoft/exchange/webservices/data/DisconnectPhoneCallRequest.java
src/main/java/microsoft/exchange/webservices/data/FindConversationRequest.java
src/main/java/microsoft/exchange/webservices/data/GetInboxRulesRequest.java
src/main/java/microsoft/exchange/webservices/data/GetPasswordExpirationDateRequest.java
src/main/java/microsoft/exchange/webservices/data/GetPhoneCallRequest.java
src/main/java/microsoft/exchange/webservices/data/GetRoomListsRequest.java
src/main/java/microsoft/exchange/webservices/data/GetRoomsRequest.java
src/main/java/microsoft/exchange/webservices/data/GetStreamingEventsRequest.java
src/main/java/microsoft/exchange/webservices/data/GetUserAvailabilityRequest.java
src/main/java/microsoft/exchange/webservices/data/GetUserOofSettingsRequest.java
src/main/java/microsoft/exchange/webservices/data/HangingServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/MultiResponseServiceRequest.java
src/main/java/microsoft/exchange/webservices/data/PlayOnPhoneRequest.java
src/main/java/microsoft/exchange/webservices/data/ServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/SetUserOofSettingsRequest.java
src/main/java/microsoft/exchange/webservices/data/SimpleServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/UpdateInboxRulesRequest.java

This PR will fix issue 28 which outlined that the response-object from an internalExecute will be closed twice which will result in an error. I also tried to add some improvement to the handling of return-parameters as well since they where just defined as Object and dont include reflection. 
This should not be merged since the functionality of the methods changed is confirmed.
Therefore help with testing would be welcome as well as your comments and suggestions.

fix: Issue 28 and add improvement for response parameters

---

src/main/java/microsoft/exchange/webservices/data/IFunctions.java
src/main/java/microsoft/exchange/webservices/data/MapiTypeConverter.java
src/main/java/microsoft/exchange/webservices/data/MapiTypeConverterMapEntry.java
src/test/java/microsoft/exchange/webservices/data/IFunctionsTest.java

It allows to:
* remove some duplicated code
* re-use thread-safe instances of IFunction interface
I also added unit tests for this changes.

Move IFunctions in separate class

---

src/main/java/microsoft/exchange/webservices/data/DateTimePropertyDefinition.java
src/main/java/microsoft/exchange/webservices/data/EwsServiceXmlReader.java
src/main/java/microsoft/exchange/webservices/data/UserConfigurationDictionary.java
src/main/java/microsoft/exchange/webservices/data/util/DateTimeUtils.java
src/test/java/microsoft/exchange/webservices/data/util/DateTimeUtilsTest.java

I continue my research with JProfiler (https://github.com/OfficeDev/ews-java-api/pull/232):
Class `DateTimeParser` creates DateTimeFormats & DateTimeFormatters (when it is instantiated). It is very expensive (see DateTimeFormat#forPattern & DateTimeFormatter#withZoneUTC). Class `DateTimeParser` is used in very critical places like `EwsServiceXmlReader`, so it is important to be as fast as possible.
Classes `DateTimeFormat` and `DateTimeFormatters` are thread-safe, so I converted DateTimeParser to utility class.

Convert DateTimeParser to DateTimeUtils

---

src/main/java/microsoft/exchange/webservices/data/ExchangeService.java
src/main/java/microsoft/exchange/webservices/data/FileAttachment.java

Fix issue #245: close stream after reading file content
avoid useless downcast in ExchangeService.getAttachments method.

Fix issue #245: close stream after reading file content

---

.travis.yml
deploy_snapshot.sh
pom.xml

- add script for completing the deployment process of snapshots for the master repo
Note: the secure vars need to be added to see this working. These must be encrypted before adding them. 
I also suggest in creating another snapshot user which only can deploy to the snapshot repo.
See this tutorial for creating of secured vars:
* [Secure-Variables](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables)
* [encryption-keys](http://docs.travis-ci.com/user/encryption-keys/)
Any comments on the change are welcome.

Autodeployment for snapshots

---

deploy_snapshot.sh
pom.xml

- sign all artifacts for deployment with gpg
- artifacts will only be sign if -Dparameter with passphrase is set
The following will **not** track gpg signature process (this will allow every user to make local builds):
```xml
mvn clean install
mvn clean deploy
```
The following will track gpg signature process:
```xml
mvn clean install -Dgpg.passphrase=myverysupersecretpassphrase
mvn clean deploy -Dgpg.passphrase=myverysupersecretpassphrase
```
* [tutorial on gpg](http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/#.VP9VPvmG-3g)

sign artifact with gpg

---

deploy_snapshot.sh

securevars where stored incorrectly. there was a gap in the definition on OSSRHPASS and OSSRH_PASS and OSSRHUSER and OSSRH_USER

mvn autodeploy

---

src/main/java/microsoft/exchange/webservices/data/core/ExchangeService.java
src/main/java/microsoft/exchange/webservices/data/core/PropertySet.java
src/main/java/microsoft/exchange/webservices/data/core/service/item/Appointment.java
src/main/java/microsoft/exchange/webservices/data/core/service/item/EmailMessage.java
src/main/java/microsoft/exchange/webservices/data/core/service/item/PostItem.java
src/main/java/microsoft/exchange/webservices/data/property/complex/ItemAttachment.java

Just another performance optimization PR:
It is not optimal to re-create array lists manually. It works much faster with Arrays.asList:
```java
public static <T> List<T> asList(T... a) {
return new ArrayList<T>(a);
}
```
As additional plus: we can write less code.

Optimize creation of collections (using Arrays.asList)

---

src/main/java/microsoft/exchange/webservices/data/autodiscover/AutodiscoverService.java
src/main/java/microsoft/exchange/webservices/data/autodiscover/configuration/outlook/OutlookConfigurationSettings.java
src/main/java/microsoft/exchange/webservices/data/core/EwsUtilities.java
src/main/java/microsoft/exchange/webservices/data/credential/WSSecurityBasedCredentials.java
src/main/java/microsoft/exchange/webservices/data/property/complex/MeetingTimeZone.java

Some inadvertent schema namespace changes have crept in through the commit 'https://github.com/OfficeDev/ews-java-api/commit/c57210dff0c8eb6cd7f7b23ae1e04e42fe516d42'.
This is to address https://github.com/OfficeDev/ews-java-api/issues/270

Reverting inadvertent namespace changes

---

src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java

Seemingly pointless annotation makes writing CI tests or enabling assertions very difficult. Have ran this in production (before this was on github) without any affects.
Example stack trace for posterity
```
java.lang.AssertionError: [ExchangeServiceBase.SaveHttpResponseHeaders] expect no headers in the dictionary yet.
at microsoft.exchange.webservices.data.EwsUtilities.EwsAssert(EwsUtilities.java:350)
at microsoft.exchange.webservices.data.ExchangeServiceBase.saveHttpResponseHeaders(ExchangeServiceBase.java:822)
at microsoft.exchange.webservices.data.ExchangeServiceBase.processHttpResponseHeaders(ExchangeServiceBase.java:813)
at microsoft.exchange.webservices.data.ExchangeServiceBase.internalProcessHttpErrorResponse(ExchangeServiceBase.java:319)
at …
```

Remove problematic assertion fixes #105

---

src/main/java/microsoft/exchange/webservices/data/credential/WSSecurityBasedCredentials.java
src/test/java/microsoft/exchange/webservices/data/credential/WSSecurityBasedCredentialsTest.java

As taken from the documentation the parameters for the XmlWriter in [java](http://docs.oracle.com/javase/7/docs/api/javax/xml/stream/XMLStreamWriter.html#writeAttribute(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String))
are different from [c#](https://msdn.microsoft.com/de-de/library/73z46xs1(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1). Also the given ns must not be null.
This PR will fix the parameters and passes in an empty string for the `namespaceURI`. 
_ref.: #265_

[WSSecurityBasedCredentials] Local name cannot be null

---

src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java

This check was removed from EWS Managed API since 2012.  Removing the check enables adding headers like OAuth.

Fix #284 to enable adding headers (e.g. OAuth)

---

src/main/java/microsoft/exchange/webservices/data/notification/StreamingSubscriptionConnection.java

- removed code of finalize method since it will provide no benefit to be
called
- removed deprecated code from dispose method since it will result in
possible errors
more information on finalize-method and a sarcasm explanation can be found here: [stackoverflow](http://stackoverflow.com/a/158370/1158046) :smiley:

dont Override finalize() and remove deprecated code in dispose(..)

---

src/main/java/microsoft/exchange/webservices/data/autodiscover/AutodiscoverService.java
src/main/java/microsoft/exchange/webservices/data/core/ExchangeService.java
src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java

Per my analysis, WebProxy even though was set in ExchangeService.java, it was not passed onto the HttpClientWebRequest request and also in case of service.autodiscoverUrl() it was not set to the instance of new AutodiscoverService.
Kindly review these changes and let me know if you guys have any feedback.
Cheers,
K

fix for https://github.com/OfficeDev/ews-java-api/issues/316

---

src/main/java/microsoft/exchange/webservices/data/core/ExchangeService.java
src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java
src/main/java/microsoft/exchange/webservices/data/core/request/GetStreamingEventsRequest.java
src/main/java/microsoft/exchange/webservices/data/core/request/ServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/core/request/SubscribeRequest.java
src/main/java/microsoft/exchange/webservices/data/core/request/UnsubscribeRequest.java

Fixes issues with subscriptions (e.g. streaming) and now uses a PoolingHttpClientConnectionManager instead of BasicHttpClientConnectionManager.
Specifically, it will create a separate PoolingHttpClientConnectionManager for subscriptions while still retaining the BasicHttpClientConnectionManager for all other connections.
New pull request of #297

Fix for Issue #276 Streaming subscription throws connection error

---

src/main/java/microsoft/exchange/webservices/data/property/complex/ComplexProperty.java
src/main/java/microsoft/exchange/webservices/data/property/complex/ComplexPropertyCollection.java
src/main/java/microsoft/exchange/webservices/data/property/complex/DictionaryProperty.java
src/main/java/microsoft/exchange/webservices/data/property/complex/IComplexPropertyChangedDelegate.java
src/test/java/microsoft/exchange/webservices/data/property/complex/ComplexPropertyCollectionTest.java

Parameter "complexProperty" is always `ComplexProperty`, I think it is unnecessary to make this check.

Remove unnecessary "instanceof" check in ComplexPropertyCollection

---

pom.xml

looking at the generated `mvn site`  maven-surefire-report will always be empty and does not contain any information because the configuration advises just to create an empty report. Removing the selected lines resolves this.

fix maven-surefire-report will always be empty

---

src/main/java/microsoft/exchange/webservices/data/core/EwsUtilities.java
src/main/java/microsoft/exchange/webservices/data/core/ExchangeService.java
src/main/java/microsoft/exchange/webservices/data/core/request/GetServerTimeZonesRequest.java
src/main/java/microsoft/exchange/webservices/data/property/complex/time/TimeZoneDefinition.java
src/main/java/microsoft/exchange/webservices/data/property/complex/time/TimeZoneTransition.java
src/test/java/microsoft/exchange/webservices/data/property/complex/TimeZoneTransitionCompareTest.java

Changes in pull request:
* EwsUtilities.PATTERN_SECONDS.
Added escape to dot PATTERN_SECONDS, otherwise it matches any char
* EwsUtilities.getXSDurationToTimeSpan()
Deleted all debug logging, because it does not bring any significant debug information and creates 8 x 108 (number of time zones) messages in debug log
* TimeZoneDefinition.compare(final TimeZoneTransition x, final TimeZoneTransition y) 
* Added type check before compare. Variable x can only be of type AbsoluteDateTransition (RelativeDayOfMonthTransition and AbsoluteDayOfMonthTransition extend AbsoluteDateTransition). 
* Variable y can be of type TimeZoneTransition, so added corresponding compare case
* TimeZoneTransition.tryReadElementFromXml()
Refactored getting periods and target groups, because method checks if array does …

Get server time zones

---

src/main/java/microsoft/exchange/webservices/data/core/EwsXmlReader.java

ref. #337
> I got the following exception when the subject of one email subject is : =?iso-8859-1?Q?=00?=
and empty appointments got the same error, I think it is also a solution to #262 
```
microsoft.exchange.webservices.data.EWSHttpException: Connection not established
at microsoft.exchange.webservices.data.HttpClientWebRequest.throwIfConnIsNull(Unknown Source)
at microsoft.exchange.webservices.data.HttpClientWebRequest.getResponseHeaders(Unknown Source)
at microsoft.exchange.webservices.data.ExchangeServiceBase.processHttpResponseHeaders(Unknown Source)
at microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(Unknown Source)
at microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(Unknown Source)
at …
```

Ewsxmlreaderfix

---

pom.xml

This PR will increment the development Version on master. All Changes related to Version 2.0.x should be placed in the 2.0.x branch. Deploying to master means that this will be included in the next Major release.

make master the development branch

---

src/main/java/microsoft/exchange/webservices/data/autodiscover/AutodiscoverDnsClient.java
src/test/java/microsoft/exchange/webservices/data/autodiscover/AutodiscoverDnsClientTest.java

The root cause here is that some (all?) auto discovery DNS lookups will return a domain name with a trailing ".". Unfortunately I don't know the why's or wherefore's, but I've seen it in a debugger connecting to live office installs. This patch strips those trailing periods and allows the auto discover process to proceed normally.

Strip trailing . from DNS lookups when converting to autodiscover url

---

src/main/java/microsoft/exchange/webservices/data/dns/DnsClient.java
src/test/java/microsoft/exchange/webservices/data/dns/DnsClientTest.java

This patch simply avoids throwing an NPE if the dnsServerAddress is not provided. This allows fallback to the system resolver.

Only attempt to set dns server if provided

---

src/main/java/microsoft/exchange/webservices/data/misc/availability/TimeWindow.java
src/test/java/microsoft/exchange/webservices/data/misc/availability/TimeWindowTest.java

This pull request resolves an issue where the ```TimeWindow``` can be incorrectly shifted because it is serialized to ```"yyyy-MM-dd'T'00:00:00"``` in the timezone of the server and deserialized in UTC. This occurs for two reasons:
* SimpleDateFormat uses the timezone of the system when a timezone has not been explicitly set
* the ```Date``` is serialized without a timezone value and a fixed time of 0:00:00, and then deserialized by [EwsServiceXmlReader.readElementValueAsUnbiasedDateTimeScopedToServiceTimeZone()](https://github.com/OfficeDev/ews-java-api/blob/1c8add6b1b3a0597a47d039157da5bb95226ff5a/src/main/java/microsoft/exchange/webservices/data/core/EwsServiceXmlReader.java#L90) which explicitly sets 'UTC' as the timezone.
Additionally, treating a date with no timezone as UTC also …

TimeWindow.writeToXmlUnscopedDatesOnly should have UTC set on formatter

---

src/main/java/microsoft/exchange/webservices/data/property/complex/recurrence/pattern/Recurrence.java
src/test/java/microsoft/exchange/webservices/data/property/complex/RecurrenceReaderTest.java

* Fix for  #380 
* MonthlyPattern and YearlyPattern methods try to read XML value using int.class instead of Integer.class.
```
reader.readElementValue(int.class);
```
* Correct form should be (used everywhere else in the class):
```
reader.readElementValue(Integer.class);
```
This had caused errors in parsing of XML

recurrence integer fix

---

src/main/java/microsoft/exchange/webservices/data/property/complex/TimeChange.java
src/test/java/microsoft/exchange/webservices/data/property/complex/TimeChangeTest.java

Pull request to fix bug in parsing AbsoluteDate and Time in TimeChange class
Bug:
* The method tryReadElementFromXml(EwsServiceXmlReader reader) tries to read XML elements AbsoluteDate and Time using  
```
SimpleDateFormat sdfin = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
```
Error:
* Then parsing of Exchange 2007 SP1 server response with MeetingTimeZone element causes following error:
```
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. Unparseable date: "03:00:00"
```
Fix Description:
* According to TimeChangeType https://msdn.microsoft.com/en-us/library/office/aa566047%28v=exchg.150%29.aspx and http://www.w3schools.com/schema/schema_dtypes_date.asp:
* Time should be of type xs:time. See …

AbsoluteDate and Time by TimeChange fix

---

src/main/java/microsoft/exchange/webservices/data/core/EwsUtilities.java
src/main/java/microsoft/exchange/webservices/data/property/definition/TimeSpanPropertyDefinition.java
src/test/java/microsoft/exchange/webservices/data/core/XSDurationTest.java

This pull request fixes the problem with wrong parsing of Bias in Period.(#357, #398 and #343)
Problem:
* TimeSpan for this one -PT3H30M will be parsed as:
```
negative true
year 0
month 30
day 0
hour 3
minute 30
seconds 0
```
* The big M for months and minutes seems to be correct according to ISO 8601 and the only difference is 'T' in the middle. For example this one ```P1Y2M10DT2H30M``` is a correct Time interval.
Fix:
* For parsing of TimeSpan, an Joda-Time Period is now used instead of row Java Regex.
* Period.parse() can automatically parse any value in form P1Y2M10DT2H30M, except of leading '-' symbol. For parsing '-' Java Regex is still used.
* Two method getXSDurationToTimeSpan() and getXSDurationToTimeSpanValue() are merged in one getXSDurationToTimeSpan(), because Joda-Time can …

XSDuration in EWSUtilities fix

---

src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java

While initializing ExchangeService object, I call method exchangeService.setWebProxy passing https proxy details. In the class ExchangeServiceBase it was not getting set.

Web Proxy set

---

pom.xml

This change runs checkstyle as part of the "verify" phase of the Maven life cycle.
Running checkstyle as part of the build process ensures that the code is always compliant with the coding standards.
See #4 for some earlier, relevant discussion.

Add checkstyle as part of the Maven build to ensure coding standards compliance

---

pom.xml
src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java
src/main/java/microsoft/exchange/webservices/data/core/request/HangingServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/core/request/HttpWebRequest.java
src/main/java/microsoft/exchange/webservices/data/core/request/ServiceRequestBase.java
src/main/java/microsoft/exchange/webservices/data/property/complex/FileAttachment.java

Add a dependency on commons-io and use it appropriately.
Unfortunately, javax.xml.stream.XMLStreamWriter doesn't implement java.io.Closeable, so IOUtils.closeQuietly couldn't be used in a few places.

Use IOUtils.closeQuietly instead of reimplementing that method in each location

---

.travis.yml
pom.xml
readme.md

this PR enables our ci-server to evaluate code coverage and submit the resulting data to [codecov.io](https://codecov.io/). Codecov is for example used by open source projects like [mockito](https://github.com/mockito/mockito/pull/314).

enable codecov.io support

---

src/main/java/microsoft/exchange/webservices/data/autodiscover/AlternateMailbox.java
src/main/java/microsoft/exchange/webservices/data/autodiscover/AlternateMailboxCollection.java
src/main/java/microsoft/exchange/webservices/data/core/XmlElementNames.java
src/test/java/microsoft/exchange/webservices/data/autodiscover/AlternateMailboxCollectionTest.java

Issue #425: Fix parsing AlternateMailboxCollection

---

src/main/java/microsoft/exchange/webservices/data/core/service/schema/ContactSchema.java

Should be "contacts:MSExchangeCertificate".
Otherwise Exchange will reject all SOAP request containing this FieldURI

Fix the "contacts:MSExchageCertificate" typo 

---

readme.md

Remove part of readme, that indicates, there isnt any stable version out yet.
Since, there is a version 2.0 out, there isnt any need for this information.

Remove unstable part in Readme

---

src/main/java/microsoft/exchange/webservices/data/core/ExchangeServiceBase.java
src/main/java/microsoft/exchange/webservices/data/core/request/ServiceRequestBase.java

After using the fix #428 to make the ExchangeService thread safe, a developer can run into a "ServiceRequestException: The request failed. Connection is still allocated".
This can be fixed by using the ExchangeServiceBase#httpPoolingClient for requests.
This Pull-Requests provides a simple differentiation between the ExchangeServiceBase#httpClient and ExchangeServiceBase#httpPoolingClient.

Added pooling for ServiceRequestBase

---

src/main/java/microsoft/exchange/webservices/data/util/TimeZoneUtils.java
src/test/java/microsoft/exchange/webservices/data/property/complex/OlsonTimeZoneTest.java

- Add more descriptive assertion failures to OlsonTimeZoneTest
- A new timezone for America/Fort_Nelson was added in tzdata2015g, which
was included in jdk8u71. This timezone had no analog in the TimeZoneUtils
map, causing the OlsonTimeZoneTest to fail.

Add America/Fort_Nelson to known OlsonTimeZones
